### ISSUE TITLE
Don't include CSS in the final html, use link tag instead.

### ISSUE THREAD

**Issue by jiniux** [Eeveelution/oldsu-stream-server#1]
```html
<style>
     {% include 'global.css' %} 
     {% include 'grid.css' %}
</style>
```
should be replaced with 
```html
<link rel="stylesheet" href="global.css">
<link rel="stylesheet" href="grid.css">
```
where both CSS files are static content, for the sake of Cloudflare caching and to avoid extra-processing on the server.

**Comment by Eeveelution** [comment]
I'll do that shortly when i redo WebsiteHandler.php, ill close this once done

**Comment by Eeveelution** [comment]
fixed in https://github.com/Eeveelution/oldsu-stream-server/commit/4b001fdf9e7c0d794f0b1f74095797fc685f9933
