### ISSUE TITLE
can't start Main.php

### ISSUE THREAD

**Issue by Zordon1337** [Eeveelution/oldsu-stream-server#2]
when i use php Main.php 
i get

> PHP Fatal error:  Uncaught ErrorException: realpath(): Passing null to parameter #1 ($path) of type string is deprecated in C:\Users\Admin\Desktop\oldsu-stream-server-master\vendor\twig\twig\src\Loader\FilesystemLoader.php:40
> Stack trace:
> #0 [internal function]: {closure}(8192, 'realpath(): Pas...', 'C:\\Users\\Admin\\...', 40)
> #1 C:\Users\Admin\Desktop\oldsu-stream-server-master\vendor\twig\twig\src\Loader\FilesystemLoader.php(40): realpath(NULL)
> #2 C:\Users\Admin\Desktop\oldsu-stream-server-master\src\Main.php(40): Twig\Loader\FilesystemLoader->__construct('C:\\Users\\Admin\\...')
> #3 {main}
>   thrown in C:\Users\Admin\Desktop\oldsu-stream-server-master\vendor\twig\twig\src\Loader\FilesystemLoader.php on line 40
> 
> Fatal error: Uncaught ErrorException: realpath(): Passing null to parameter #1 ($path) of type string is deprecated in C:\Users\Admin\Desktop\oldsu-stream-server-master\vendor\twig\twig\src\Loader\FilesystemLoader.php:40
> Stack trace:
> #0 [internal function]: {closure}(8192, 'realpath(): Pas...', 'C:\\Users\\Admin\\...', 40)
> #1 C:\Users\Admin\Desktop\oldsu-stream-server-master\vendor\twig\twig\src\Loader\FilesystemLoader.php(40): realpath(NULL)
> #2 C:\Users\Admin\Desktop\oldsu-stream-server-master\src\Main.php(40): Twig\Loader\FilesystemLoader->__construct('C:\\Users\\Admin\\...')
> #3 {main}
>   thrown in C:\Users\Admin\Desktop\oldsu-stream-server-master\vendor\twig\twig\src\Loader\FilesystemLoader.php on line 40
> 

i'm using php 8.1.6
composer ver: 2.3.7

**Comment by Eeveelution** [comment]
dont care
